# Generated by Django 4.2.3 on 2023-08-10 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=50, verbose_name="New Word")),
                (
                    "source_language",
                    models.CharField(max_length=5, verbose_name="Source language code"),
                ),
                (
                    "target_language",
                    models.CharField(max_length=5, verbose_name="Target language code"),
                ),
                (
                    "translation",
                    models.CharField(max_length=50, verbose_name="Translation"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
