# Generated by Django 4.2.3 on 2023-08-10 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0003_word_delete_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 10, 16, 40, 41, 954905)
            ),
        ),
    ]
