# Generated by Django 4.2.3 on 2023-08-10 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "AdvancedDict",
            "0008_newword_sourcelanguagefull_alter_newword_timestamp_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newword",
            name="sourceLanguageFull",
        ),
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 10, 22, 23, 45, 379692)
            ),
        ),
    ]
