# Generated by Django 4.2.3 on 2023-08-10 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0009_remove_newword_sourcelanguagefull_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newword",
            name="translation_edited",
            field=models.CharField(
                default="3", max_length=500, verbose_name="Displayed translation"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 11, 0, 14, 41, 379790)
            ),
        ),
    ]
