# Generated by Django 4.2.3 on 2023-08-12 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0011_alter_newword_timestamp_quiz_question_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="diffcutly",
            new_name="diffculty",
        ),
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 18, 34, 16, 265141)
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 18, 34, 16, 265141)
            ),
        ),
    ]
