# Generated by Django 4.2.3 on 2023-08-12 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0013_rename_diffculty_quiz_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 19, 9, 54, 298980)
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="difficulty",
            field=models.IntegerField(
                choices=[("Easy", 3), ("Medium", 6), ("Hard", 10)],
                default=3,
                verbose_name="Difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 19, 9, 54, 299974)
            ),
        ),
    ]
