# Generated by Django 4.2.3 on 2023-08-12 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0016_alter_newword_timestamp_alter_quiz_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 19, 23, 6, 175659)
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="difficulty",
            field=models.IntegerField(
                choices=[(0, "Easy"), (1, "Normal"), (2, "Hard")],
                default=0,
                verbose_name="Difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="score",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 19, 23, 6, 175659)
            ),
        ),
    ]
