# Generated by Django 4.2.3 on 2023-08-12 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0017_alter_newword_timestamp_alter_quiz_difficulty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newword",
            name="quiz",
            field=models.ManyToManyField(
                related_name="questions", to="AdvancedDict.quiz"
            ),
        ),
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 20, 4, 22, 328331)
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionsz",
                to="AdvancedDict.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 20, 4, 22, 328331)
            ),
        ),
    ]
