# Generated by Django 4.2.3 on 2023-08-12 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0018_newword_quiz_alter_newword_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newword",
            name="quiz",
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                related_name="quiz", to="AdvancedDict.newword"
            ),
        ),
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 20, 7, 9, 987572)
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 12, 20, 7, 9, 988106)
            ),
        ),
    ]
