# Generated by Django 4.2.3 on 2023-08-14 11:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0021_answer_user_alter_newword_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 13, 7, 14, 29969)
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 13, 7, 14, 29969)
            ),
        ),
    ]
