# Generated by Django 4.2.3 on 2023-08-14 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0023_alter_newword_timestamp_alter_quiz_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 13, 7, 34, 124025)
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 13, 7, 34, 124025)
            ),
        ),
    ]
