# Generated by Django 4.2.3 on 2023-08-14 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0025_remove_answer_user_alter_newword_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="asked",
            field=models.CharField(default="Day", max_length=50, verbose_name="Asked"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 17, 32, 18, 931197)
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 17, 32, 18, 939649)
            ),
        ),
    ]
