# Generated by Django 4.2.3 on 2023-08-14 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0027_answer_question_alter_newword_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="asked",
        ),
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 17, 48, 18, 21649)
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 17, 48, 18, 21649)
            ),
        ),
    ]
