# Generated by Django 4.2.3 on 2023-08-14 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0028_remove_answer_asked_alter_newword_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 17, 48, 20, 351906)
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 17, 48, 20, 351906)
            ),
        ),
    ]
