# Generated by Django 4.2.3 on 2023-08-14 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("AdvancedDict", "0029_alter_newword_timestamp_alter_quiz_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="question",
        ),
        migrations.AlterField(
            model_name="newword",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 17, 54, 22, 691886)
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 14, 17, 54, 22, 691886)
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="answer",
                to="AdvancedDict.newword",
            ),
            preserve_default=False,
        ),
    ]
