languages = [
    ('Afrikaans', 'af'),
    ('Albanian', 'sq'),
    ('Amharic', 'am'),
    ('Arabic', 'ar'),
    ('Armenian', 'hy'),
    ('Azerbaijani', 'az'),
    ('Basque', 'eu'),
    ('Belarusian', 'be'),
    ('Bengali', 'bn'),
    ('Bosnian', 'bs'),
    ('Bulgarian', 'bg'),
    ('Catalan', 'ca'),
    ('Cebuano', 'ceb'),
    ('Chichewa', 'ny'),
    ('Chinese (Simplified)', 'zh-CN'),
    ('Chinese (Traditional)', 'zh-TW'),
    ('Corsican', 'co'),
    ('Croatian', 'hr'),
    ('Czech', 'cs'),
    ('Danish', 'da'),
    ('Dutch', 'nl'),
    ('English', 'en'),
    ('Esperanto', 'eo'),
    ('Estonian', 'et'),
    ('Filipino', 'tl'),
    ('Finnish', 'fi'),
    ('French', 'fr'),
    ('Frisian', 'fy'),
    ('Galician', 'gl'),
    ('Georgian', 'ka'),
    ('German', 'de'),
    ('Greek', 'el'),
    ('Gujarati', 'gu'),
    ('Haitian Creole', 'ht'),
    ('Hausa', 'ha'),
    ('Hawaiian', 'haw'),
    ('Hebrew', 'iw'),
    ('Hindi', 'hi'),
    ('Hmong', 'hmn'),
    ('Hungarian', 'hu'),
    ('Icelandic', 'is'),
    ('Igbo', 'ig'),
    ('Indonesian', 'id'),
    ('Irish', 'ga'),
    ('Italian', 'it'),
    ('Japanese', 'ja'),
    ('Javanese', 'jw'),
    ('Kannada', 'kn'),
    ('Kazakh', 'kk'),
    ('Khmer', 'km'),
    ('Kinyarwanda', 'rw'),
    ('Korean', 'ko'),
    ('Kurdish (Kurmanji)', 'ku'),
    ('Kyrgyz', 'ky'),
    ('Lao', 'lo'),
    ('Latin', 'la'),
    ('Latvian', 'lv'),
    ('Lithuanian', 'lt'),
    ('Luxembourgish', 'lb'),
    ('Macedonian', 'mk'),
    ('Malagasy', 'mg'),
    ('Malay', 'ms'),
    ('Malayalam', 'ml'),
    ('Maltese', 'mt'),
    ('Maori', 'mi'),
    ('Marathi', 'mr'),
    ('Mongolian', 'mn'),
    ('Myanmar (Burmese)', 'my'),
    ('Nepali', 'ne'),
    ('Norwegian', 'no'),
    ('Odia (Oriya)', 'or'),
    ('Pashto', 'ps'),
    ('Persian', 'fa'),
    ('Polish', 'pl'),
    ('Portuguese', 'pt'),
    ('Punjabi', 'pa'),
    ('Romanian', 'ro'),
    ('Russian', 'ru'),
    ('Samoan', 'sm'),
    ('Scots Gaelic', 'gd'),
    ('Serbian', 'sr'),
    ('Sesotho', 'st'),
    ('Shona', 'sn'),
    ('Sindhi', 'sd'),
    ('Sinhala', 'si'),
    ('Slovak', 'sk'),
    ('Slovenian', 'sl'),
    ('Somali', 'so'),
    ('Spanish', 'es'),
    ('Sundanese', 'su'),
    ('Swahili', 'sw'),
    ('Swedish', 'sv'),
    ('Tajik', 'tg'),
    ('Tamil', 'ta'),
    ('Tatar', 'tt'),
    ('Telugu', 'te'),
    ('Thai', 'th'),
    ('Turkish', 'tr'),
    ('Turkmen', 'tk'),
    ('Ukrainian', 'uk'),
    ('Urdu', 'ur'),
    ('Uyghur', 'ug'),
    ('Uzbek', 'uz'),
    ('Vietnamese', 'vi'),
    ('Welsh', 'cy'),
    ('Xhosa', 'xh'),
    ('Yiddish', 'yi'),
    ('Yoruba', 'yo'),
    ('Zulu', 'zu'),
    ('Hebrew', 'he'),
    ('Chinese (Simplified)', 'zh')
]

language_codes = [
    'af', 'sq', 'am', 'ar', 'hy', 'az', 'eu', 'be', 'bn', 'bs', 
    'bg', 'ca', 'ceb', 'ny', 'zh-CN', 'zh-TW', 'co', 'hr', 'cs', 'da', 
    'nl', 'en', 'eo', 'et', 'tl', 'fi', 'fr', 'fy', 'gl', 'ka', 'de', 
    'el', 'gu', 'ht', 'ha', 'haw', 'iw', 'hi', 'hmn', 'hu', 'is', 'ig', 
    'id', 'ga', 'it', 'ja', 'jw', 'kn', 'kk', 'km', 'rw', 'ko', 'ku', 
    'ky', 'lo', 'la', 'lv', 'lt', 'lb', 'mk', 'mg', 'ms', 'ml', 'mt', 
    'mi', 'mr', 'mn', 'my', 'ne', 'no', 'or', 'ps', 'fa', 'pl', 'pt', 
    'pa', 'ro', 'ru', 'sm', 'gd', 'sr', 'st', 'sn', 'sd', 'si', 'sk', 
    'sl', 'so', 'es', 'su', 'sw', 'sv', 'tg', 'ta', 'tt', 'te', 'th', 
    'tr', 'tk', 'uk', 'ur', 'ug', 'uz', 'vi', 'cy', 'xh', 'yi', 'yo', 
    'zu', 'he', 'zh'
]